### PR TITLE
Fix rubocop

### PR DESCRIPTION
**Pull request by PierreRambaud**
Travis is broken, rubocop failed and rspec failed too.

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Is there anyone here ? :/

**Comment by PierreRambaud** [comment]
PR updated.

**Comment by smtlaissezfaire** [comment]
Cool I'll look to merge tomorrow night

**Comment by smtlaissezfaire** [comment]
Weird - this fails tests for me.  

Check out fileutils.rb - how can _options be renamed to options without changing the method signature? - this code should be failing, so I'm not sure what's going on with travis.

Even after changing that, I get a ton of warnings from rubocop

**Comment by PierreRambaud** [comment]
I don't really understand what do you mean by changing the method signature because the signature is already changed: https://github.com/defunkt/fakefs/pull/268/files#diff-d5a65988bf0acd1827873927a12eb005L6
Do you use the latest commit `1b7ae46ac24086e0a256500bb68c020c2e8c1439`?

**Comment by smtlaissezfaire** [comment]
Ah, I thought I just needed the last commit.  Can you rebase onto current master?

**Comment by PierreRambaud** [comment]
Logically be good, waiting for travis ;)

**Pull request closed without merging**
