### PR TITLE
Ensure Kernel#open remains private

### LINKED ISSUE #312: Kernel hijacking and open-uri failures
FakeFS and `open-uri`’s `Kernel.open` don’t work well together.

Introduced in #226; related to #290.

cc @dekz, @eventualbuddha 

Requiring `open-uri` before or after `fakefs` changes the error message. Also note that I don’t even call `FakeFS.activate!`. If I add it (before `FakeFS.deactivate!`), the error message is the same.

```rb
# test1.rb
require 'open-uri'
require 'fakefs/safe'

FakeFS.deactivate!

Kernel.open('/tmp/existing-file')
```
```
Code/fakefs ‹2.2.3p173› ‹master*› » ruby test1.rb
/Users/bquorning/.rubies/ruby-2.2.3/lib/ruby/2.2.0/open-uri.rb:28:in `open': wrong number of arguments (0 for 1+) (ArgumentError)
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `call'
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `block (2 levels) in unhijack!'
  from /Users/bquorning/.rubies/ruby-2.2.3/lib/ruby/2.2.0/open-uri.rb:30:in `open'
  from test1.rb:7:in `<main>'
```

```rb
# test2.rb
require 'fakefs/safe'
require 'open-uri'

FakeFS.deactivate!

Kernel.open('/tmp/existing-file')
```
```
Code/fakefs ‹2.2.3p173› ‹master*› » ruby test2.rb
/Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `initialize': wrong number of arguments (0 for 1..3) (ArgumentError)
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `open'
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `call'
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `block (2 levels) in unhijack!'
  from /Users/bquorning/.rubies/ruby-2.2.3/lib/ruby/2.2.0/open-uri.rb:30:in `open'
  from test2.rb:7:in `<main>'
```

### PR DESCRIPTION
**Pull request by jacobat**
Appears to fix #312.

### CODE REVIEW

**Comment by bquorning** [comment]
:+1: and it looks more understandable than #313.

**Comment by bquorning** [comment]
Build will be fixed by #320.

**Comment by dekz** [comment]
LGTM

**Comment by grosser** [comment]
@eventualbuddha can we get this merged ?

**Comment by grosser** [comment]
@smtlaissezfaire can we get this merged ?

**Pull request merged**
